### ISSUE TITLE
Can not run with --net=host

### ISSUE THREAD

**Issue by dieuit07** [orientechnologies/orientdb-docker#16]
Hi everyone, When I try run net=host. container run with no PORT

```
docker run --net=host -d --name orientdb --restart=always -p 2424:2424 -p 2480:2480 -v /home/docker_data/orientdb/databases:/orientdb/databases -e ORIENTDB_ROOT_PASSWORD=rootpwd orientdb:latest
```
=> PORTS is null

+ And when run with option 
```
-v /home/docker_data/orientdb/config:/orientdb/config
```
PORTS is available, but site localhost:2480 => This site can’t be reached

+ And I can't exec to container: 
```
docker exec -it orientdb /bin/bash
```
=> exec: "/bin/bash": stat /bin/bash: no such file or directory

+ And can not connect by plocal:
```
create database remote:172.17.0.2/db1 root rootpwd
disconnect
connect plocal:../v4 root rootpwd
=> Cannot open the storage 'v4' because it does not exist in path: ../v4
	DB name="v4"

OR

connect plocal:/home/docker_data/orientdb/databases/v4 root rootpwd
=> Cannot open the storage 'v4' because it does not exist in path: ../v4
	DB name="v4"
```

**Comment by robfrank** [comment]
I don't know waht is supposed to do the --net flag. Can you point me to docker docs section about that?

If you providde a config volume, the volume MUST contains a valid config set for orientdb. It is useful when config is managed externally, by tools such as chef, puppet and so on.

I don't know WHERE you run the docker container. On plain linux, usually localhost:2480 works, but if you run docker inside a VM (like on Mac Toolbox)  you need to point to <default machine address>:2480. 

Orient is based on Alpine, maybe it doesn't contain bash. Try /bin/sh

Latest topic, I'm sorry, I don't understand what are you doing.

**Comment by robfrank** [comment]
no response for too much time
