### ISSUE TITLE
Is the Spatial version available on Docker Hub? 

### ISSUE THREAD

**Issue by Darren-Bell** [orientechnologies/orientdb-docker#18]
Hi 
From my limited knowledge it doesn't appear to be available there. Would it be possible to make it available?

Regards
Darren

**Comment by robfrank** [comment]
Hi, no the spatial docker image is not yet available on docker hub, you can build the image by your own using the updated Dokerfile in the dedicated folder.
Spatial rely on a LGPL library called JTS, we are investigating if we che release on docker hub or not.
