### ISSUE TITLE
Better description when use a config volume

### ISSUE THREAD

**Issue by rottmann** [orientechnologies/orientdb-docker#19]
Please change the doc so that it is obvious what happen, when we start the container with a config volume.
Or add an option, that the default docker config will be stored there and not a basic config, if no config is found.

I am an orientdb noob and was really confused because the black box container didn't do anything.

**Comment by robfrank** [comment]
A config volume is useful to provide to the container a custom configuration set. It is a well konwn practice in the Docker's world, AFAIK.
I can improve the doc. 
What do you mean with "the black box container didn't do anything" ?

**Comment by rottmann** [comment]
Great thanks! Would save others some time :)

When i add a config volume the container start but e.g. i can't use the webinterface.

**Comment by robfrank** [comment]
If you provide a config volume it MUST contains  config set. It will override the config set bundled with the container. Note that the docker image is ONLY the orientdb tar.gz packaged as a container. The only big difference is that there's not a demo database inside.
