### ISSUE TITLE
website: download-page has wrong docker run code (typo)

### ISSUE THREAD

**Issue by aJonathanSchneider** [orientechnologies/orientdb-docker#20]
There is a tiny typo on this webpage: http://orientdb.com/download/
if you copy the docker-run code, it shows two different kinds of dashes for --name, like so:
`docker run -d —-name orientdb -p 2424:2424 -p 2480:2480 -e ORIENTDB_ROOT_PASSWORD=root orientdb:latest`
I'm using chrome with Windows 10. Using the same dash as with the other parameters solves it. Unfortunately it's at a point where beginners might stumble over that

**Comment by robfrank** [comment]
The site is now fixed. Sorry for the inconvenience and thank you very much for the issue.
