### ISSUE TITLE
Can't connect to OrientDB Studio

### ISSUE THREAD

**Issue by AxelRHD** [orientechnologies/orientdb-docker#23]
Can't connect to the Studio via network. Port (2480) is listening but the connection is refused.

**Comment by robfrank** [comment]
Can you post more details? Host OS, docker command line, image version, all  details matter. Thanks

**Comment by AxelRHD** [comment]
Host: Ubuntu (headless) Server 16.04
Kernel: 4.4.0-47-generic
Version (in console): 2.2.13
Startup: `docker run --name=orientdb_test --volume=/var/orientdb/test/config:/orientdb/config --volume=/var/orientdb/test/databases:/orientdb/databases --volume=/var/orientdb/test/backup:/orientdb/backup --publish=2424:2424 --publish=2480:2480 --env=ORIENTDB_ROOT_PASSWORD=pwd orientdb`

I found also a warning on startup: `WARNI onAfterDynamicPlugins() Configuration document is empty [ODefaultServerSecurity]`

Thanks for the support.

**Comment by robfrank** [comment]
in the volume /var/orientdb/test/config do you provide a configuration file set? 
If you provide an empty dir, the default conf inside the container isn't used, and orientdb will start with the minimun config set created at runtime. 

https://github.com/docker-library/docs/tree/master/orientdb

**Comment by AxelRHD** [comment]
Okay, got it. I removed the volume for config. Now I've tried to download one of the public databases. I get a browser message "Authentication required      For http://<ip-address>:2480 username and password is required     The connection to this website is not secure". I can't donwload it.

**Comment by robfrank** [comment]
http://2480 !??!?! maybe you forgot the host address? http://localhost:2480 or, if deployed on another server/host, http://ip_address_of_host:2480/

**Comment by AxelRHD** [comment]
Of course I used the ip-address. The editor of github didn't show it because I wrote it in "<" ">" above.

**Comment by robfrank** [comment]
to download the database you need to provide the database root username and password.
Son, I think "root", and the password provided on the CLI: ORIENTDB_ROOT_PASSWORD=pwd

**Comment by AxelRHD** [comment]
The download of the public databases didn't work. But I created a testing-environment on my own.
