### ISSUE TITLE
Implement Docker health check 

### ISSUE THREAD

**Issue by robfrank** [orientechnologies/orientdb-docker#28]
Reference docs:

https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by stuartpb** [comment]
It looks like this was added and then... [removed](https://github.com/orientechnologies/orientdb-docker/commit/2b6305aa0293796280c27be782d2710d68fc74b6)? Any insights as to why?

I'm currently looking at [a patch to add HEALTHCHECK to the RethinkDB Dockerfiles](https://github.com/rethinkdb/rethinkdb-dockerfiles/pull/36), and I'm trying to understand how other official images have done it.

**Comment by robfrank** [comment]
You're right, was added and then removed. The docker team asked me to remove during the pr:

https://github.com/docker-library/official-images/pull/2831

Pointing to this comment:

https://github.com/docker-library/cassandra/pull/76#issuecomment-246054271

So, even it seems a good idea, the docker team doesn't think it is: I don't think you will find an official image with health-check defined.
