### ISSUE TITLE
TcpIpJoinerOverAWS class missing from orientdb 2.2.30 docker image

### ISSUE THREAD

**Issue by bipulkarnani** [orientechnologies/orientdb-docker#35]
I am getting following error: com.hazelcast.core.HazelcastException: java.lang.ClassNotFoundException: com.hazelcast.cluster.impl.TcpIpJoinerOverAWS

**Comment by luigidellaquila** [comment]
Hi @bipulkarnani 

yes, it's a known issue in 2.2.30, we already fixed it, so the latest snapshot should work fine on AWS.
The fix will be released with 2.2.31

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @bipulkarnani 

It's pretty hard to change an already released package (ie we cannot control all the Maven mirrors and update them).
Anyway, we are scheduling 2.2.31 in a few days, so it shouldn't be a long wait

Thanks

Luigi
