### ISSUE TITLE
Documentation: ORIENTDB_ROOT_PASSWORD

### ISSUE THREAD

**Issue by chris-martin** [orientechnologies/orientdb-docker#4]
The 2.1.5 image on Docker Hub seems to require an ORIENTDB_ROOT_PASSWORD environment variable, so I imagine there ought to be a readme that mentions this.

**Comment by robfrank** [comment]
This repo is a WIP to create official docker images. You can find the docs here: https://github.com/orientechnologies/docker-docs/blob/master/orientdb/content.md

Let me know if the doc is ok

**Comment by metanomy** [comment]
Following the instructions for orientdb:latest with the ORIENTDB_ROOT_PASSWORD correctly adds the password to the orientdb_server_config.xml file, but:
- Grateful Dead db isn't present
- Using "root" and that password doesn't work for logging into Studio, nor for adding new dbs (neither online nor local).

**Comment by chris-martin** [comment]
Yep, that doc explains it fine. Just needs to be linked to from https://hub.docker.com/r/orientdb/orientdb/ somewhere.

**Comment by robfrank** [comment]
As said, this is a work in progress. We are working to produce an official docker image, so doc is targete for that. 
The image will not contain any sample database.
