### ISSUE TITLE
Version 3.0.0 on Docker library hub?

### ISSUE THREAD

**Issue by anthony-o** [orientechnologies/orientdb-docker#43]
I tried to use Docker image `orientdb:3.0.0` without success and found that https://hub.docker.com/r/library/orientdb/ actually didn't contain the version 3.0.0 of OrientDB.

Do you know when this is planned to be deployed?

**Comment by luigidellaquila** [comment]
Hi @anthony-o 

We are releasing it now, it will take a few hours to very few days

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @anthony-o 

OrientDB v 3.0 is available for download on the website.
We also submitted the docker image for approval to DockerHub, hopefully in next 24 hours it will be available

Thanks

Luigi
