### ISSUE TITLE
Tinkerpop port not exposed

### ISSUE THREAD

**Issue by remi-sap** [orientechnologies/orientdb-docker#57]
Hi,
I don't see a port for tinkerpop in the [docker file.](https://github.com/orientechnologies/orientdb-docker/blob/5320d6580dcfb23750e69f9009e5bb81ccfbe517/3.0-tp3/x86_64/alpine/Dockerfile)

Did I miss something ?

**Comment by luigidellaquila** [comment]
Hi @remi-sap 

You are right, I think we have to fix it, I'll do it ASAP

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @remi-sap 

I just fixed it and sent the PR to DockerHub, next release (v 3.0.17) will have this fix

Thanks

Luigi

**Comment by remi-sap** [comment]
Excellent, thanks !
