### ISSUE TITLE
Which signal orientdb handles for gracefully shutdown 

### ISSUE THREAD

**Issue by samkhamk** [orientechnologies/orientdb-docker#67]
Hello There,

Sorry this is not proper channel but I want to know which signal orientdb handles for gracefully shutdown SIGINT SIGTERM or SIGKILL
which I can mention in docker file to build orientdb  image.

Regards,
SAM

**Comment by tglman** [comment]
Hi,
this may help : https://github.com/orientechnologies/orientdb/blob/develop/core/src/main/java/com/orientechnologies/orient/core/OSignalHandler.java#L64  right now `SIGKILL`, `SIGHUP`,`SIGINT`,`SIGTERM` cause all the graceful shutdown, be aware that `SIGKILL` my be intercepted by the OS e remove the process without telling anything to it.
