### ISSUE TITLE
Docker hub supports only 3.2.28

### ISSUE THREAD

**Issue by GaleSS** [orientechnologies/orientdb-docker#75]
Though, in github last released version is 3.2.29, latest version that is supported by dockerhub is 3.2.28.
Also, in readme link to official docker image is https://hub.docker.com/r/orientdb/orientdb/ but it leads to nowhere, docker link for official orientdb image is https://hub.docker.com/_/orientdb/

**Comment by GaleSS** [comment]
Apparently, docker hub is looking not on master branch of the repo. Guys, please fix the issue.

**Comment by tglman** [comment]
Is updated now, closing
