### ISSUE TITLE
Cannot connect to DB

### ISSUE THREAD

**Issue by CyborTronik** [orientechnologies/orientdb-docker#8]
Using latest version of https://hub.docker.com/r/orientdb/orientdb/
and specifying ORIENTDB_ROOT_PASSWORD.
Do container is starting fine and I'm opening the studio page. But absolutely can't login and create new DBs.

**Comment by lvca** [comment]
Looks like the OrientDB user have no rights to create the database at filesystem level.

**Comment by CyborTronik** [comment]
I've created the DB through REST API. But from Studio is not possible to do that.

**Comment by lvca** [comment]
For OrientDB user I meant the OS user.

**Comment by robfrank** [comment]
Hi, just tested. I'm able to create a db using root credentials.
If you use volumes, you should be sure that the user you use to launch the docker image has the rights to write on the volume you provide to the container.
